urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.index, name='index'), #一覧ページ
    path('add/', views.add, name='add'), #追加ページ
    path('update/<int:pk>/', views.update, name='update'), #更新ページ
    path('delete/<int:pk>', views.delete, name='delete'), #削除ページ
    path('detail/<int:pk>', views.detail, name='detail'), #詳細ページ

]

models.py
from django.db import models
from django.utils import timezone
from . import textToWordcloud as ttwc


import pdb

class Day(models.Model):
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateField('日付', default=timezone.now)

    #wordcloud_image =ttwc.create_wordcloud_ja(text)

forms.py
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'

views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DayCreateForm
from .models import Day
from . import textToWordcloud as ttwc
import oseti

def index(request):
    """
    日記の一覧を表示
    """
    text_datas = ''
    datas = Day.objects.all()
    #print(Day.objects.all())
    for data in datas:
        text_datas += data.text

    ttwc.create_wordcloud_ja(10001,text_datas)


    context = {
        'day_list':Day.objects.all(),
    }
    return render(request, 'diary/day_index.html', context)



def add(request):

    """
    日記の記事を追加
    """
    # 送信内容を元にフォームを作る。POSTじゃなければ空のフォームを作成。
    form = DayCreateForm(request.POST or None)
    print(request.POST)
    print(type(request.POST))

    #print(request.POST)

    # method==POSTとは送信ボタンが押されたとき。form.is_validは入力内容に問題が無い場合Trueになる。
    if request.method == 'POST' and form.is_valid():
        #入力時にtextを取得しそのtextを画像に変換
        form.save()
        #print(form)
        return redirect('diary:index')

    # 通常時のアクセスや入力内容に誤りがあれば、再度day_form.htmlを表示
    context = {
        'form':form
    }
    return render(request, 'diary/day_form.html', context)


def update(request, pk):
    """
    日記の記事を変更
    """
    # urlのpkを基に、Dayを取得（pkはidと同じ）
    day = get_object_or_404(Day, pk=pk)

    # formに取得したDayを紐づける
    form = DayCreateForm(request.POST or None, instance=day)

    # method=POST(送信ボタン押下)、でかつ、入力内容に問題がなければフォームを保存する。
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    # 通常時のアクセスや入力内容に問題があった場合は最初のページを表示
    context = {
        'form':form
    }
    return render(request, 'diary/day_form.html', context)


def delete(request, pk):
    """
    日記の記事を削除
    """
    # URLのPKを基に、Dayを取得（pkはidと同じ）
    day = get_object_or_404(Day, pk=pk)

    # method=POST(送信ボタン押下)
    if request.method == 'POST':
        day.delete()
        return redirect('diary:index')

    # 通常時のアクセス。または問題があった場合のアクセス。
    context = {
        'day':day
    }
    return render(request, 'diary/day_delete.html', context)


def detail(request, pk):
    """
    日記の詳細ページ
    """
    #　URLのPKを基に、Dayを取得
    day = get_object_or_404(Day, pk=pk)
    text = day.text
    ttwc.create_wordcloud_ja(pk,text)
    #word_cloud_image = '../../wordcloud/'+str(pk)+'.png'

    context = {
        'day':day ,
        #'word_cloud':word_cloud_image
    }
    return render(request, 'diary/day_detail.html', context)

templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>

    <title>日記アプリケーション</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
     <link rel="stylesheet" href="../../../media/css/base.css" >

  </head>
  <!-- <body> -->

    <div class="container">
      <nav class="nav">

        <a class="nav-link active" href="{% url 'diary:index' %}">一覧</a>
        <a class="nav-link" href="{% url 'diary:add' %}">追加</a>
      </nav>
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

templates/diary/chutorialAjax.html
<!doctype html>
<html lang="ja">
  <head>
    <title>Ajax</title>
  </head>
  <body>
      <div class="container">
          <h2>数値の入力</h2>
          <form id="ajax-number" action="{% url 'blog:ajax_number' %}" method="POST">
              {% csrf_token %}
              <input type="number" id="number1" required>
              <input type="number" id="number2" required>
              <button type="submit" >計算</button>
          </form>

          <h2>数値の計算</h2>
          <div class="result">
          </div>
      </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        $('#ajax-number').on('submit', function(e) {
            e.preventDefault();

            $.ajax({
                'url': '{% url "blog:ajax_number" %}',
                'type': 'POST',
                'data': {
                    'number1': $('#number1').val(),
                    'number2': $('#number2').val(),
                },
                'dataType': 'json'
            })
            .done(function(response){
                $('.result').prepend('<p>引き算結果：' + response.minus + '</p>');
                $('.result').prepend('<p>足し算結果：' + response.plus + '</p>');
            });
        });
    </script>
  </body>
</html>

templates/diary/day_delete.html
{% extends 'diary/base.html' %}
{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit" class="btn btn-primary">削除</button>
    {% csrf_token %}
</form>
{% endblock %}

templates/diary/day_detail.html
{% extends 'diary/base.html' %}
{% block content %}
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="{% static "/base.css" %}" rel="stylesheet"  >
</head>

    <table class="table">

        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text | linebreaksbr}}</td>
        </tr>
        <tr>
            <th>wordCloud</th>
            <td><img id ="image_place" src = "" />  </td>
            <script>
                // img要素を取得する
                let img = document.getElementById("image_place")
                img.src = "../../../media/images/"+ {{day.pk}} +".png"
              </script>

        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
        </tr>
    </table>
    <a href="{% url 'diary:update' day.pk %}"><button class="btn btn-primary">更新</button></a>
    <a href="{% url 'diary:delete' day.pk %}"><button class="btn btn-danger">削除</button></a>

{% endblock %}

templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="tabel">
        <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ form.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
    </table>

    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

templates/diary/day_index.html
{% extends 'diary/base.html' %}

{% block content %}

<h1>日記一覧</h1>

<table class="table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
            <th>更新処理</th>
            <th>削除処理</th>
        </tr>
    </thead>
    <tbody>
    {% for day in day_list %}
        <tr>
            <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
            <td>{{ day.date }}</td>
            <td><a href="{% url 'diary:update' day.pk %}">更新</a></td>
            <td><a href="{% url 'diary:delete' day.pk %}">削除</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>


<div> 総評</div>
<img id ="image_place" src = "" />
            <script>
                // img要素を取得する
                let img = document.getElementById("image_place")
                img.src = "../../../media/images/10001.png"
              </script>

{% endblock %}

templates/diary/singleton.html
{% extends 'diary/base.html' %}
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
{% block content %}
{% load static %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="{% static "/base.css" %}" rel="stylesheet"  >
<script>
// CSRF対策
const getCookie = (name) => {
    if (document.cookie && document.cookie !== '') {
      for (const cookie of document.cookie.split(';')) {
        const [key, value] = cookie.trim().split('=')
        if (key === name) {
          return decodeURIComponent(value)
        }
      }
    }
  }
  const csrftoken = getCookie('csrftoken')

// 記事追加
const form_fetch= document.getElementById("form_fetch")
form_fetch.addEventListener('submit', (e) => {
    e.preventDefault()
    const url = 'http://127.0.0.1:8000/diary/api/'
    const post_title = document.getElementById('post_title')
    const post_text = document.getElementById("text_form")
    // URLのクエリパラメータを管理
    const body = new URLSearchParams()
    body.append('title', post_title.value)
    body.append('text',post_text.value)
    fetch(url, {
      method: 'POST',
      body: body,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
        'X-CSRFToken': csrftoken,
      },
    })
      .then((response) => {
        console.log('toriaezudekiteru')
        // JSON形式に変換
        return response.json()
      })
      .then((response) => {
        console.log('toriaezudekiteru')
      })
      .catch((error) => {
        console.log(error)
      })
  })
</script>

</head>




<form id = "form_fetch" action =""method="POST">
  <table class="tabel">
      <div> Title
          <input type="text" id='post_title' maxlength="8" size="10">

      </div>
          <div>本文
          <input type="text" id="text_form" required
        maxlength="300" size="100">
          </div>


  </table>

  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %}
</form>

<div id="result">
  <tr>
    <th>wordCloud</th>
    <!--<td><img id ="image_place" src = "" />  </td>

    <td>{{image.image}} </td> -->
    <td><img id ="image_place" src = "" />  </td>
    <script>
        // img要素を取得する
        let img = document.getElementById("image_place")
        img.src = "../../../media/images/spa.png"
      </script>

    <div class="ImgResult">
    </div>
</tr>
</div>


{% endblock %}